apiVersion: v1
kind: Service
metadata:
  name: {{ include "resdiary-webapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "resdiary-webapp.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ include "resdiary-webapp.chart" . }}
    resdiary.com/scrape-metrics: "true"
spec:
  type: {{ .Values.service.type | quote }}
  ports:
  - port: 80
    targetPort: web
    name: web
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.webNodePort }}
{{- end }}
  - port : 3030
    targetPort: metrics
    name: metrics
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.metricsNodePort }}
{{- end }}
  - port : 52024
    targetPort: grpc
    name: grpc
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.grpcNodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "resdiary-webapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}